name: Generate Images
on:
  push:
    tags:
      - "*"

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create input/output folder
        run: |
          mkdir images
          mkdir source
          find . -type f \( -name "*.yaml" -o -name "*.md" -o -name "*.tf" -o -name "*.bicep" -o -name "*.json" \) -exec mv -t source/ -- {} +
      - name: Generate Images
        uses: sharadcodes/code-snap-action@v1.0
        with:
          source_folder: "source"
          output_folder: "images"
          syntax_theme: "emacs"
      - name: Get generated images
        run: |
          echo "IMAGES<<EOF" >> $GITHUB_ENV
          echo "|" >> $GITHUB_ENV
          echo "$(find images -name "*" -type f)" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
        id: get_images
      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ env.IMAGES }}
